"""Feature engineering utilities shared across training and online inference."""

from __future__ import annotations

from typing import List, Tuple

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler


def split_features_and_target(
    df: pd.DataFrame,
    target_column: str,
    exclude_columns: List[str],
    categorical_columns: List[str],
) -> Tuple[pd.DataFrame, pd.Series, List[str], List[str]]:
    """Split dataframe into features/target and derive column groups."""
    X = df.drop(columns=[target_column])
    y = df[target_column]

    dropped = [col for col in exclude_columns if col in X.columns]
    if dropped:
        X = X.drop(columns=dropped)

    categorical = [col for col in categorical_columns if col in X.columns]
    numerical = [col for col in X.columns if col not in categorical]

    return X, y, numerical, categorical


def build_feature_transformer(
    categorical_columns: List[str],
    numerical_columns: List[str],
) -> ColumnTransformer:
    """Create a ColumnTransformer with standard numeric scaling and one-hot encoding."""
    transformers = []
    if numerical_columns:
        transformers.append(("numerical", StandardScaler(), numerical_columns))
    if categorical_columns:
        encoder = OneHotEncoder(handle_unknown="ignore", sparse=False)
        transformers.append(("categorical", encoder, categorical_columns))

    return ColumnTransformer(transformers=transformers)


def get_feature_names(
    transformer: ColumnTransformer,
    numerical_columns: List[str],
    categorical_columns: List[str],
) -> List[str]:
    """Return feature names generated by the fitted transformer."""
    feature_names: List[str] = []

    if numerical_columns:
        feature_names.extend(numerical_columns)

    if categorical_columns and "categorical" in transformer.named_transformers_:
        encoder = transformer.named_transformers_["categorical"]
        if hasattr(encoder, "get_feature_names_out"):
            feature_names.extend(encoder.get_feature_names_out(categorical_columns).tolist())
        elif hasattr(encoder, "get_feature_names"):
            feature_names.extend(encoder.get_feature_names(categorical_columns).tolist())
        else:
            feature_names.extend(categorical_columns)

    return feature_names
